<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Persistence\Redis\" />
    <Folder Include="Services\Redis\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.0" />
    <PackageReference Include="MassTransit.Abstractions" Version="9.1.0" />
    <PackageReference Include="MassTransit.MongoDb" Version="9.1.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.26" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.7" />
    <PackageReference Include="MongoDB.Bson" Version="3.8.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.8.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hokm.Application\Hokm.Application.csproj" />
    <ProjectReference Include="..\Hokm.Domain\Hokm.Domain.csproj" />
  </ItemGroup>

</Project>
